const ServicesData = [
  {
    id: 1,
    icon: "bi bi-server",
    title: "Software Development",
    slug: "software-development",
    color: "blue",
    category: [
      "Hire PHP Developers",
      "Hire React Developers",
      "Hire Software Developers",
      "Hire Laravel Developers",
      "Hire AngularJS Developers",
      "Hire Java Software Developers",
      "Hire AI and ML Developers",
      "Hire Software Testing and QAExperts",
      "Hire Progressive Web App Developer",
      "Hire Umbraco Developer",
    ],
    description:
      "Software development is the art and science of designing, coding, testing, and maintaining computer programs and applications. It involves translating ideas into functional software solutions that cater to specific needs and requirements. This dynamic field fuels technological innovation, underpinning everything from mobile apps to complex business systems, driving progress in our digital world.",
  },
  {
    id: 2,
    icon: "bi bi-globe2",
    title: "Website Development",
    slug: "website-development",
    color: "red",
    category: [
      "Hire Web Designer",
      "Hire Frontend Developers",
      "Hire Backend Developers",
      "Hire Full Stack Developer",
      "Hire Node Js Developer",
      "Hire Vue Js Developers",
      "Hire Shopify Developers",
      "Hire HTML 5 Developers",
      "Hire Phython Developers",
      "Hire Ruby on Rails Developers",
      "Hire Drupal Developers",
      "Hire Wordpress Developers",
      "Hire Magento Developers",
    ],
    description:
      "Website development involves the design, coding, and maintenance of websites to ensure they function seamlessly on the internet. It encompasses a wide range of tasks, from creating the website's structure and layout to implementing interactive features and ensuring compatibility across different devices and browsers. Effective website development is crucial for establishing a strong online presence, engaging visitors, and achieving specific goals, whether they are related to business, information dissemination, or online communities. It combines creativity with technical expertise to deliver user-friendly and visually appealing websites that meet the needs of both site owners and their audiences.",
  },
  {
    id: 3,
    icon: "bi bi-android2",
    title: "Apps Development",
    slug: "apps-development",
    color: "pink",
    category: [
      "Hire Flutter App Developer",
      "Hire Android App Developer",
      "Hire IOS App Developers",
      "Hire IOS Game Developers",
      "Hire Android Game Developers",
      "Hire Ionic App Developers",
      "Hire Xamarin App Developers",
      "Hire React Native App Developers",
    ],
    description:
      "App development involves the process of designing, coding, and launching software applications for various platforms, such as mobile devices, desktops, and the web. App developers use programming languages and tools to create functional and user-friendly applications that serve specific purposes, from productivity and entertainment to solving practical problems. The rapid evolution of technology has made app development a pivotal force in the digital landscape, enabling businesses and individuals to connect with users, streamline processes, and enhance daily life through intuitive and innovative software solutions.",
  },

  {
    id: 4,
    icon: "bi bi-megaphone",
    title: "Digital Marketing",
    slug: "digital-marketing",
    color: "orange",
    category: [
      "Hire SEO Expert",
      "Hire Content Writer",
      "Hire Email Marketing Expert",
      "Hire Google Analytics Expert",
    ],
    description:
      "Digital marketing is a strategic approach to promoting products, services, or brands using digital channels and technologies. It encompasses activities such as search engine optimization (SEO), social media marketing, email marketing, content creation, and online advertising. Digital marketing leverages the power of the internet to reach and engage target audiences, track performance metrics, and optimize campaigns for maximum impact. In today's digital age, it is a vital component of any successful marketing strategy, allowing businesses to connect with customers, drive conversions, and stay competitive in the digital landscape.",
  },

  {
    id: 5,
    icon: "bi bi-brush-fill",
    title: "UI / UX Design",
    slug: "ui-ux-design",
    color: "purple",
    category: [
      "Hire Graphic Designer",
      "Hire Web Designer",
      "Hire UI/UX Designer",
    ],
    description:
      "UI (User Interface) and UX (User Experience) design are disciplines focused on creating optimal digital interactions. UI design primarily deals with the visual and interactive aspects of a digital product, ensuring it is visually appealing and easy to navigate. UX design, on the other hand, focuses on the overall user journey, aiming to make it seamless, intuitive, and enjoyable. Together, they aim to create user-centric and visually pleasing digital experiences that meet both functional and aesthetic requirements.",
  },
  {
    id: 6,
    icon: "bi bi-laptop",
    title: "IT Outsourcing",
    slug: "it-outsourcing",
    color: "green",
    category: [
      {
        id: 1,
        icon: "bi bi-slack",
        slug: "software-development",
        name: "Software Development",
      },
      {
        id: 2,
        slug: "website-development",
        icon: "bi bi-globe",
        name: "Web Development",
      },
      {
        id: 3,
        slug: "apps-development",
        icon: "bi bi-android2",
        name: "Mobile App Development",
      },
      {
        id: 5,
        slug: "ui-ux-design",
        icon: "bi bi-brush-fill",
        name: "Graphics & Web Designing",
      },
      {
        id: 8,
        slug: "digital-marketing",
        icon: "bi bi-megaphone",
        name: "Digital Marketing",
      },
      {
        id: 6,
        slug: "it",
        icon: "bi bi-gear-fill",
        name: "IT Technical Support",
      },
      {
        id: 7,
        slug: "virtual",
        icon: "bi bi-headset",
        name: "Virtual Assistant",
      },
    ],
    description:
      "IT outsourcing refers to the practice of delegating certain technology-related tasks, services, or projects to external service providers. This strategic business decision allows organizations to leverage the expertise, resources, and cost-efficiency of external specialists, often located in different geographic regions. IT outsourcing can encompass a wide range of services, such as software development, technical support, infrastructure management, and more. By outsourcing IT functions, companies can focus on their core operations while benefiting from specialized skills and cost savings.",
  },
];

export const ProductsData = [
  {
    id: 1,
    icon: "bi bi-clipboard-data-fill",
    slug: "point-of-sales-software",
    logo: "/img/brands/1.png",
    type: "featured",
    tag: "Retail Market",
    social: {
      fb: "",
      twitter: "https://twitter.com/Dokanpos",
      youtube: "",
      linkedin: "https://www.linkedin.com/showcase/dokanpos-pos-software",
    },
    title: "Point of Sales Software",
    projectName: "Dokan Pos",
    projectUrl: "https://dokanpos.com",
    watchUrl:
      "https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FDokanpos%2Fvideos%2F1406391740297377%2F&show_text=false&width=560&t=0",
    description:
      "Point of sale (POS) software is a specialized application designed to streamline and manage retail transactions. It enables businesses to efficiently process sales, track inventory, accept payments, generate receipts, and often includes reporting and analytics tools for better business management. POS software helps businesses improve customer service, reduce errors, and gain insights into their sales data, ultimately enhancing overall operational efficiency and profitability.",
    category: [
      {
        id: 1,
        name: "Employee Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 2,
        name: "Customer Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 3,
        name: "Suppliers Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 4,
        name: "Product Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 5,
        name: "Barcode Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 6,
        name: "Purchase Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 7,
        name: "Inventory Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 8,
        name: "Invoicing/Sales Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 9,
        name: "Accounts Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 10,
        name: "Repairing",
        icon: "bi bi-check-circle icon",
      },
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 9,
    icon: "bi bi-coin",
    slug: "micro-credit-management-software",
    logo: "/img/brands/4.1.png",
    tag: "Finance Industry",
    type: "featured",
    title: "Micro Credit Management Software",
    projectName: "Easy Somiti",
    projectUrl: "https://easysomity.com",
    watchUrl: "https://www.youtube.com/embed/CvkJqCvYrXE?si=6I6_ZT8pa1D8FjN1",
    description:
      "Micro Credit Management Software is a digital solution designed for microfinance institutions and organizations that provide small-scale loans to individuals and small businesses. It helps in automating and managing the entire microcredit lifecycle, including loan origination, disbursement, repayment tracking, and reporting. Additionally, it often includes features for client data management, risk assessment, and portfolio analysis, improving the efficiency and accuracy of microcredit operations. This software enables microfinance institutions to serve their clients more effectively, reduce administrative overhead, and make informed lending decisions.",
    features: [
      "Employee Management",
      "Customer Management",
      "Loan Management",
      "DPS Management",
      "FDR Management",
      "Package Management",
      "Daily/ Weekly/ Monthly Collection",
      "Reporting",
      "Easy to Use",
      "SMS Integration",
      "Data Backup",
      "Multi Language",
      "Mobile App",
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },

  {
    id: 3,
    icon: "bi bi-x-diamond",
    slug: "freight-forwarding-software",
    title: "Freight forwarding Software",
    projectName: "CFFMS",
    logo: "/img/brands/7.png",
    type: "featured",
    tag: "Logistic Industry",
    type: "featured",
    description:
      "Freight forwarding software is a digital tool tailored for logistics companies and freight forwarders to efficiently manage and optimize the shipment of goods. It streamlines tasks such as cargo tracking, documentation, scheduling, cost calculation, and communication with carriers and clients. This software enhances supply chain visibility, automates processes, and improves overall efficiency in the freight forwarding industry.",
    features: [
      "Agent Management",
      "Consignee Management",
      "Shipper Management",
      "Notify Management",
      "Sea Import Management",
      "Sea Export Management",
      "Air Import Management",
      "Air Export Management",
      "Booking /Quantity /Container",
      "Bill of Lading/EPB/Master",
      "Shipment Advice",
      "Cargo Manifest",
      "Income Management",
      "Expanse Management",
      "Credit Note Management",
      "Debit Note Management",
      "Invoice Management",
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 4,
    icon: "bi bi-building-fill-add",
    slug: "hospital-management-software",
    logo: "/img/brands/3.png",
    type: "featured",
    title: "Hospital Management Software",
    tag: "Health Industry",
    projectName: "Lab Master",
    watchUrl: "https://www.youtube.com/embed/0bPljx7uBG4?si=o6bFVpAW1bwz-I2r",
    description:
      "Hospital Management Software is a comprehensive digital solution designed for healthcare institutions to streamline and optimize their administrative and clinical processes. It helps manage patient information, appointments, billing, inventory, and electronic health records (EHR). Additionally, it often includes features for staff scheduling, reporting, and analytics, enhancing operational efficiency, patient care, and overall management of healthcare facilities. This software facilitates better coordination among various departments and improves the overall quality of healthcare services provided by hospitals.",
    features: [
      "Doctor Management",
      "Nurse Management",
      "Patient Management",
      "Staff Management",
      "Reception",
      "Patient Billing",
      "Doctor Appointment",
      "Pathology Management",
      "Radiology Management",
      "Indoor Management",
      "Outdoor Management",
      "Bed/Wards Management",
      "Reference Management",
      "Account Management",
      "Pharmacy Management",
      "Prescription Management",
      "SMS Integration",
      "Notice Board",
      "Patient Smart Card",
      "Blood Bank",
      "Document Management",
      "Ambulance Management",
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },

  {
    id: 5,
    icon: "bi bi-capsule",
    slug: "pharmacy-management-software",
    logo: "/img/brands/1.png",
    title: "Pharmacy Management Software",
    tag: "Health Industry",
    projectName: "Dokan Pos",
    social: {
      fb: "",
      twitter: "https://twitter.com/Dokanpos",
      youtube: "",
      linkedin: "https://www.linkedin.com/showcase/dokanpos-pos-software",
    },
    description:
      "Pharmacy Management Software is a digital solution designed for pharmacies and drugstores to efficiently manage various aspects of their operations. It helps in inventory management, prescription processing, patient records, billing, and compliance with regulations. Additionally, it often includes features for drug interaction checks, medication history, and insurance claim processing, enhancing patient safety and customer service. This software streamlines pharmacy workflows, reduces errors, and improves the overall management of pharmaceutical processes, ultimately leading to better patient care and operational efficiency.",
    features: [
      "Employee Management",
      "Customer Management",
      "Suppliers Management",
      "Medicine Management",
      "Barcode Management",
      "Purchase Management",
      "Sales Management",
      "Inventory Management",
      "Minimum Stock Alert",
      "Stock Adjustment",
      "Account Management",
      "Reporting",
      "SMS Integration",
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 6,
    icon: "bi bi-car-front-fill",
    slug: "parking-management-software",
    logo: "/img/brands/8.png",
    title: "Parking Management Software",
    tag: "Logistic Industry",
    projectName: "Parking Buzz",
    description:
      "Parking Management Software is a specialized digital tool used by parking facilities, such as garages and lots, to efficiently manage and control their parking operations. It helps in automating tasks like vehicle entry and exit, payment processing, space allocation, and reporting. Additionally, it often includes features like license plate recognition, reservation systems, and real-time occupancy tracking, enhancing the overall efficiency and user experience in parking facilities. This software allows parking operators to optimize space utilization, improve security, and provide a smoother parking experience for customers.",
    features: [
      "Employee Management",
      "Parking Place Management",
      "Parking Category",
      "TimeZone Setting",
      "Parking Group Setup",
      "Vehicle Manage",
      "Parking In / out",
      "Billing Collection",
      "Reports",
    ],
  },
  // {
  //   id: 6,
  //   icon: "bi bi-car-front-fill",
  //   slug: "parking-management-software",
  //   logo: "/img/brands/8.png",
  //   title: "Poin Management Software",
  //   projectName: "Parking Buzz",
  //   description:
  //     "Parking Management Software is a specialized digital tool used by parking facilities, such as garages and lots, to efficiently manage and control their parking operations. It helps in automating tasks like vehicle entry and exit, payment processing, space allocation, and reporting. Additionally, it often includes features like license plate recognition, reservation systems, and real-time occupancy tracking, enhancing the overall efficiency and user experience in parking facilities. This software allows parking operators to optimize space utilization, improve security, and provide a smoother parking experience for customers.",
  //   features: [
  //     "Employee Management",
  //     "Parking Place Management",
  //     "Parking Category",
  //     "TimeZone Setting",
  //     "Parking Group Setup",
  //     "Vehicle Manage",
  //     "Parking In / out",
  //     "Billing Collection",
  //     "Reports",
  //   ],
  // },
  {
    id: 7,
    icon: "bi bi-truck",
    slug: "courier-management-software",
    logo: "/img/brands/5.png",
    type: "featured",
    tag: "Logistic Industry",
    title: "Courier Management Software",
    projectName: "Courier Lab",
    watchUrl:
      "https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2Fcourierlab.software%2Fvideos%2F912846656990062%2F&show_text=false&width=560&t=0",
    description:
      "Courier Management Software is a digital solution designed to streamline and optimize the operations of courier and delivery services. It helps manage orders, track shipments, optimize routes, handle scheduling, and automate billing and reporting. Additionally, it often includes features for real-time tracking, proof of delivery, and customer communication, improving efficiency and transparency in the courier industry. This software enables courier companies to enhance their service quality, reduce costs, and provide a better experience for their clients.",
    features: [
      "Merchant Management",
      "Rider Management",
      "Hub/Branch/Agent",
      "Call Center Management",
      "Accounts Management",
      "Manager Management",
      "Merchant Wise Price",
      "Order Manage",
      "Reschedule, Partial & Exchange Delivery",
      "Pick Up Auto Assign",
      "Branch Wise Collection",
      "Merchant Api Integration",
      "Bulk Import",
      "Problem Management",
      "Rider Commission",
      "Employee Attendance",
      "Hub/Branch Commission",
      "Expanse Management",
      "Income Management",
      "SMS Integration",
      "Merchant App",
      "Rider App",
      "Pathao/Redx Api Integration",
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 8,
    icon: "bi bi-file-text-fill",
    slug: "prescription-management-system",
    logo: "/img/brands/11.png",
    title: "Prescription Management System",
    tag: "Health Industry",
    projectName: "RX",
    description:
      "A Prescription Management System is specialized software designed for healthcare providers and pharmacies to efficiently manage and process medication prescriptions. It helps healthcare professionals electronically generate, store, and transmit prescriptions, ensuring accuracy and compliance with regulations. Additionally, it often includes features for patient records, drug interactions, and medication history, improving patient safety and care. This system streamlines the prescription workflow, reduces errors, and enhances the overall management of medication-related processes in healthcare settings.",
    features: [
      "Dose, Rules & Duration Management",
      "Patient List",
      "Referral List",
      "Electronic Medical Records",
      "Consultant Fee Collection",
      "Prescription Template",
      "Customized Prescription",
      "Printing",
      "Patient Lifetime Records",
      "Easy to Use",
      "SMS Integration",
      "Multi Language",
      "Data Backup",
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },

  // {
  //   id: 2,
  //   icon: "bi bi-ui-checks",
  //   slug: "restaurant-management-software",
  //   logo: "/img/brands/2.png",
  //   tag: "Retail Market",
  //   title: "Restaurant Management Software",
  //   projectName: "Resto Pos",
  //   watchUrl: "https://www.youtube.com/embed/eA-Wptq6VpQ?si=gfjcU7wCLGNSQf7n",
  //   description:
  //     "Restaurant management software is a comprehensive digital solution tailored for the foodservice industry. It facilitates efficient restaurant operations by automating tasks such as order management, reservations, table assignments, menu updates, staff scheduling, and inventory tracking. Additionally, it often includes features for payment processing, customer relationship management (CRM), and analytics to enhance decision-making and customer service. Restaurant management software empowers establishments to improve efficiency, reduce costs, and provide a better dining experience for their patrons.",
  //   features: [
  //     "Employee Management",
  //     "Table Reservation",
  //     "Kitchen Management",
  //     "Order Management",
  //     "Inventory Management ",
  //     "Collection Management",
  //     "Customer Management",
  //     "Analytics and reporting",
  //     "Sales and menu analytics",
  //   ],
  //   images: [
  //     "/product/pos/1.png",
  //     "/product/pos/2.png",
  //     "/product/pos/3.png",
  //     "/product/pos/4.png",
  //     "/product/pos/5.png",
  //     "/product/pos/6.png",
  //   ],
  // },
  {
    id: 10,
    icon: "bi bi-scissors",
    slug: "education-management-system",
    logo: "/img/brands/12.png",
    type: "featured",
    tag: "Education Industry",
    title: "Education Management System",
    projectName: "Student Care",
    description:
      "A School Management System (SMS) is a comprehensive software solution designed to streamline the administrative and academic operations of educational institutions. This system integrates various functions such as student enrollment, attendance tracking, grade management, timetable scheduling, and communication between teachers, students, and parents. It also includes features for managing staff records, payroll, and library resources. By centralizing data and automating routine tasks, the SMS enhances efficiency, improves data accuracy, and facilitates better decision-making, ultimately fostering a more organized and productive educational environment.",
    features: [
      "Master Setup",
      "Front Office",
      "Student Management",
      "Admission Management",
      "Academic Management",
      "Behavior Record",
      "Admit & Id Card",
      "Class & Exam Management",
      "Lesson Plan Management",
      "Result Management",
      "Marksheet & Certificate",
      "Document Management",
      "HR Payroll Management",
      "Fee Management",
      "Income & Expense",
      "SMS Integration",
      "Holiday Calendar",
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },

  {
    id: 11,
    icon: "bi bi-scissors",
    slug: "tailor-management-system",
    logo: "/img/brands/10.png",
    title: "Tailor Management System",
    projectName: "Expert Tailor",
    tag: "Garments Industry",
    description:
      "A Tailor Management System is a specialized software tool used in the fashion and garment industry to streamline and enhance the tailoring and clothing alteration process. It helps manage customer information, track clothing orders, process alterations, and facilitate communication between tailors, customers, and fashion boutiques. Additionally, it often includes features for inventory management, invoicing, and reporting, improving the efficiency and accuracy of tailoring services. This system plays a crucial role in the fashion and garment industry, ensuring that customers receive high-quality tailored clothing with precision and style.",
    features: [
      "Customer  Management",
      "Order Receive",
      "Production Update",
      "Ready To Delivery",
      "Bill Collection & Delivery",
      "Report Management",
      "SMS Integration",
      "Data Backup",
    ],
  },

  {
    id: 12,
    icon: "bi bi-hospital",
    slug: "clinic-management-system",
    logo: "/img/brands/lab-master.png",
    title: "Clinic Management System",
    tag: "Health Industry",
    description:
      "A Clinic Management System is a specialized software tool used in healthcare to streamline and enhance the diagnostic testing process. It helps manage patient information, track test orders, process results, and facilitate communication between healthcare providers and diagnostic laboratories. Additionally, it often includes features for quality control, data analysis, and reporting, improving the accuracy and efficiency of diagnostic procedures. This system plays a crucial role in healthcare settings, ensuring that patients receive timely and accurate diagnostic information for effective medical decision-making.",
    features: [
      "Doctor",
      "Patient",
      "Reception",
      "Appointment",
      "Pathology",
      "Accounts",
    ],
  },
  // {
  //   id: 11,
  //   icon: "bi bi-recycle",
  //   slug: "enterprise-resource-planning-erp",
  //   logo: "",
  //   title: "Enterprise Resource Planning (ERP)",
  //   description:
  //     "Enterprise Resource Planning (ERP) is an integrated software solution used by businesses to manage and streamline various core processes and functions, including finance, human resources, inventory management, supply chain, manufacturing, and more. ERP software provides a centralized database and a suite of applications that enable data sharing and real-time communication across different departments. Its primary goal is to improve operational efficiency, facilitate data-driven decision-making, and enhance overall business performance by providing a comprehensive view of an organization's processes and resources.",
  //   features: [],
  // },
  {
    id: 13,
    icon: "bi bi-calendar-check",
    slug: "event-management-software",
    logo: "/img/brands/9.png",
    type: "featured",
    title: "Event Management Software",
    tag: "Corporate Industry",
    projectName: "Event Pro",
    description:
      "Event Management Software is a comprehensive digital tool designed for planning and executing events of all types and sizes. It provides features to facilitate event organization, such as creating event schedules, managing guest lists, handling ticketing, and coordinating event logistics. This software streamlines the entire event lifecycle, from planning and promotion to registration and post-event analysis. Event managers rely on it to ensure smooth and successful events, whether they are conferences, weddings, trade shows, or any other gathering, making it an indispensable asset for the event planning industry.",
    features: [
      "Visitor Management",
      "Exhibitor Management",
      "Speaker Management",
      "Guest  Management",
      "Event Schedule",
      "Id Card Print",
      "Event Countdown",
      "Attraction Management",
      "Event Booking",
      "Sponsor Management",
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 14,
    icon: "bi bi-people-fill",
    slug: "customer-relationship-management",
    logo: "/img/brands/6.png",
    type: "featured",
    title: "Customer Relationship Management",
    tag: "Corporate Industry",
    projectName: "SMART CRM 360",
    description:
      "Customer Relationship Management (CRM) refers to a strategy and software system that helps businesses effectively manage and nurture their interactions and relationships with customers. CRM software provides tools for storing and analyzing customer data, tracking communication history, managing sales and marketing efforts, and improving customer service. The goal of CRM is to enhance customer satisfaction, increase sales, and drive long-term customer loyalty by providing a better understanding of customer needs and preferences.",
    features: [
      "Employee management",
      "Product management",
      "Customer Management",
      "Leads Management",
      "Followup Management",
      "Proposal Management",
      "Project Management",
      "Tasks Management",
      "Invoices Management",
      "Subscription",
      "Collection",
      "Tickets Management",
      "Document Management",
      "Holiday Calendar",
      "Reminder",
      "Expanses",
      "Income",
      "Knowledge Base",
      "Jobs",
      "Interview Schedule",
      "Offer Letters",
      "Candidate Database",
      "Attendances",
      "Leave",
      "Salary Generate",
      "Database Backup",
      "SMS Integration",
      "Multi Language",
      "Report Management",
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 15,
    icon: "bi bi-people-fill",
    slug: "multivendor-ecomeerce-software",
    logo: "/img/brands/6.png",
    type: "featured",
    title: "Multivendor Ecommerce Software",
    tag: "Ecommerce Industry",
    projectName: "GIFT ShOP",
    description:
      "Multivendor ecommerce software allows multiple vendors to register, list, and sell products on a single platform, providing a streamlined experience for customers. Key features include vendor management with comprehensive dashboards, product management with bulk upload capabilities, and order processing with secure payment gateways. The software also offers customer reviews, detailed analytics, and a centralized admin panel for marketplace operators to manage vendor activities, transactions, and inventory efficiently. This solution is ideal for creating a diverse and scalable online marketplace.",
    features: [
      "Vendor Registration",
      "Vendor Profiles",
      "Vendor Dashboard",
      "Product Listings",
      "Product Uploads",
      "Product Variations",
      "Inventory Management",
      "Order Tracking",
      "Order Fulfillment",
      "Return and Refund Processing",
      "Customer Accounts",
      "Customer Reviews and Ratings",
      "Customer Support",
      "Secure Payment Gateways",
      "Shipping Calculations",
      "Shipping Integrations",
      "Delivery Tracking",
      "Discount and Coupon Management",
      "Email Marketing Integration",
      "SEO Tools",
      "Sales Reports",
      "Vendor Performance Analytics",
      "Customer Behavior Analytics",
      "Vendor-Customer Messaging",
      "Data Encryption",
      "User Access Controls",
      "Fraud Detection",
      "Centralized Admin Dashboard",
      "Vendor Approval Workflow",
      "Ticket Management",
      "Knowledge Base",
      "User Guides and Documentation",
      "Third-Party App Integrations",
      "API Access",
    ],

    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 16,
    icon: "bi bi-people-fill",
    slug: "multivendor-ecomeerce-gift-shop",
    logo: "/img/brands/6.png",
    title: "Multivendor Ecommerce For Gift Shop",
    projectName: "GIFT ShOP",
    tag: "Ecommerce Industry",
    description:
      "Multivendor ecommerce software allows multiple vendors to register, list, and sell products on a single platform, providing a streamlined experience for customers. Key features include vendor management with comprehensive dashboards, product management with bulk upload capabilities, and order processing with secure payment gateways. The software also offers customer reviews, detailed analytics, and a centralized admin panel for marketplace operators to manage vendor activities, transactions, and inventory efficiently. This solution is ideal for creating a diverse and scalable online marketplace.",
    features: [
      "Vendor Registration",
      "Vendor Profiles",
      "Vendor Dashboard",
      "Product Listings",
      "Product Uploads",
      "Product Variations",
      "Inventory Management",
      "Order Tracking",
      "Order Fulfillment",
      "Return and Refund Processing",
      "Customer Accounts",
      "Customer Reviews and Ratings",
      "Customer Support",
      "Secure Payment Gateways",
      "Shipping Calculations",
      "Shipping Integrations",
      "Delivery Tracking",
      "Discount and Coupon Management",
      "Email Marketing Integration",
      "SEO Tools",
      "Sales Reports",
      "Vendor Performance Analytics",
      "Data Encryption",
      "User Access Controls",
      "Fraud Detection",
      "Centralized Admin Dashboard",
      "Vendor Approval Workflow",
      "Ticket Management",
      "Knowledge Base",
      "User Guides and Documentation",
      "Third-Party App Integrations",
      "API Access",
    ],

    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 17,
    icon: "bi bi-people-fill",
    slug: "multivendor-ecomeerce-medicine",
    logo: "/img/brands/6.png",
    title: "Multivendor Ecommerce For Medicine",
    tag: "Ecommerce Industry",
    projectName: "GIFT ShOP",
    description:
      "Multivendor ecommerce software allows multiple vendors to register, list, and sell products on a single platform, providing a streamlined experience for customers. Key features include vendor management with comprehensive dashboards, product management with bulk upload capabilities, and order processing with secure payment gateways. The software also offers customer reviews, detailed analytics, and a centralized admin panel for marketplace operators to manage vendor activities, transactions, and inventory efficiently. This solution is ideal for creating a diverse and scalable online marketplace.",
    features: [
      "Vendor Registration",
      "Vendor Profiles",
      "Vendor Dashboard",
      "Product Listings",
      "Product Uploads",
      "Product Variations",
      "Inventory Management",
      "Order Tracking",
      "Order Fulfillment",
      "Return and Refund Processing",
      "Customer Accounts",
      "Customer Reviews and Ratings",
      "Customer Support",
      "Secure Payment Gateways",
      "Shipping Calculations",
      "Shipping Integrations",
      "Delivery Tracking",
      "Discount and Coupon Management",
      "Email Marketing Integration",
      "SEO Tools",
      "Sales Reports",
      "Vendor Performance Analytics",
      "Data Encryption",
      "User Access Controls",
      "Fraud Detection",
      "Centralized Admin Dashboard",
      "Vendor Approval Workflow",
      "Ticket Management",
      "Knowledge Base",
      "User Guides and Documentation",
      "Third-Party App Integrations",
      "API Access",
    ],

    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 18,
    icon: "bi bi-truck",
    slug: "courier-management-software",
    logo: "/img/brands/5.png",
    tag: "Logistic Industry",
    title: "Domestic Courier Management Software",
    tag: "Logistic Industry",
    projectName: "Courier Lab",
    watchUrl:
      "https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2Fcourierlab.software%2Fvideos%2F912846656990062%2F&show_text=false&width=560&t=0",
    description:
      "Domestic Courier Management Software is a digital solution designed to streamline and optimize the operations of courier and delivery services. It helps manage orders, track shipments, optimize routes, handle scheduling, and automate billing and reporting. Additionally, it often includes features for real-time tracking, proof of delivery, and customer communication, improving efficiency and transparency in the courier industry. This software enables courier companies to enhance their service quality, reduce costs, and provide a better experience for their clients.",
    features: [
      "Merchant Management",
      "Rider Management",
      "Hub/Branch/Agent",
      "Call Center Management",
      "Accounts Management",
      "Manager Management",
      "Merchant Wise Price",
      "Order Manage",
      "Reschedule, Partial & Exchange Delivery",
      "Pick Up Auto Assign",
      "Branch Wise Collection",
      "Merchant Api Integration",
      "Bulk Import",
      "Problem Management",
      "Rider Commission",
      "Employee Attendance",
      "Hub/Branch Commission",
      "Expanse Management",
      "Income Management",
      "SMS Integration",
      "Merchant App",
      "Rider App",
      "Pathao/Redx Api Integration",
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 19,
    icon: "bi bi-truck",
    slug: "international-courier-management-software",
    logo: "/img/brands/5.png",
    tag: "Logistic Industry",
    tag: "Logistic Industry",
    title: "International Courier Management Software",
    projectName: "Courier Lab",
    watchUrl:
      "https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2Fcourierlab.software%2Fvideos%2F912846656990062%2F&show_text=false&width=560&t=0",
    description:
      "International Courier Management Software is a digital solution designed to streamline and optimize the operations of courier and delivery services. It helps manage orders, track shipments, optimize routes, handle scheduling, and automate billing and reporting. Additionally, it often includes features for real-time tracking, proof of delivery, and customer communication, improving efficiency and transparency in the courier industry. This software enables courier companies to enhance their service quality, reduce costs, and provide a better experience for their clients.",
    features: [
      "Merchant Management",
      "Rider Management",
      "Hub/Branch/Agent",
      "Call Center Management",
      "Accounts Management",
      "Manager Management",
      "Merchant Wise Price",
      "Order Manage",
      "Reschedule, Partial & Exchange Delivery",
      "Pick Up Auto Assign",
      "Branch Wise Collection",
      "Merchant Api Integration",
      "Bulk Import",
      "Problem Management",
      "Rider Commission",
      "Employee Attendance",
      "Hub/Branch Commission",
      "Expanse Management",
      "Income Management",
      "SMS Integration",
      "Merchant App",
      "Rider App",
      "Pathao/Redx Api Integration",
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 20,
    icon: "bi bi-scissors",
    slug: "point-of-sales-software",
    logo: "/img/brands/10.png",
    title: "Fashion House Management System",
    projectName: "Fashion House",
    tag: "Garments Industry",
    description:
      "A Fashion House Management System is a specialized software tool used in the fashion and garment industry to streamline and enhance the tailoring and clothing alteration process. It helps manage customer information, track clothing orders, process alterations, and facilitate communication between tailors, customers, and fashion boutiques. Additionally, it often includes features for inventory management, invoicing, and reporting, improving the efficiency and accuracy of tailoring services. This system plays a crucial role in the fashion and garment industry, ensuring that customers receive high-quality tailored clothing with precision and style.",
    category: [
      {
        id: 1,
        name: "Employee Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 2,
        name: "Customer Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 3,
        name: "Suppliers Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 4,
        name: "Product Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 5,
        name: "Barcode Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 6,
        name: "Purchase Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 7,
        name: "Inventory Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 8,
        name: "Invoicing/Sales Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 9,
        name: "Accounts Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 10,
        name: "Repairing",
        icon: "bi bi-check-circle icon",
      },
    ],
  },
  {
    id: 21,
    icon: "bi bi-clipboard-data-fill",
    slug: "point-of-sales-software",
    logo: "/img/brands/1.png",
    tag: "Retail Market",
    social: {
      fb: "",
      twitter: "https://twitter.com/Dokanpos",
      youtube: "",
      linkedin: "https://www.linkedin.com/showcase/dokanpos-pos-software",
    },
    title: "Pharmacy Pos",
    projectName: "Dokan Pos",
    projectUrl: "https://dokanpos.com",
    watchUrl:
      "https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FDokanpos%2Fvideos%2F1406391740297377%2F&show_text=false&width=560&t=0",
    description:
      "Pharmacy Point of sale (POS) software is a specialized application designed to streamline and manage retail transactions. It enables businesses to efficiently process sales, track inventory, accept payments, generate receipts, and often includes reporting and analytics tools for better business management. POS software helps businesses improve customer service, reduce errors, and gain insights into their sales data, ultimately enhancing overall operational efficiency and profitability.",
    category: [
      {
        id: 1,
        name: "Employee Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 2,
        name: "Customer Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 3,
        name: "Suppliers Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 4,
        name: "Product Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 5,
        name: "Barcode Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 6,
        name: "Purchase Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 7,
        name: "Inventory Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 8,
        name: "Invoicing/Sales Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 9,
        name: "Accounts Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 10,
        name: "Repairing",
        icon: "bi bi-check-circle icon",
      },
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 22,
    icon: "bi bi-clipboard-data-fill",
    slug: "point-of-sales-software",
    logo: "/img/brands/1.png",
    tag: "Retail Market",
    social: {
      fb: "",
      twitter: "https://twitter.com/Dokanpos",
      youtube: "",
      linkedin: "https://www.linkedin.com/showcase/dokanpos-pos-software",
    },
    title: "Super Shop Pos",
    projectName: "Dokan Pos",
    projectUrl: "https://dokanpos.com",
    watchUrl:
      "https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FDokanpos%2Fvideos%2F1406391740297377%2F&show_text=false&width=560&t=0",
    description:
      "Super Shop Point of sale (POS) software is a specialized application designed to streamline and manage retail transactions. It enables businesses to efficiently process sales, track inventory, accept payments, generate receipts, and often includes reporting and analytics tools for better business management. POS software helps businesses improve customer service, reduce errors, and gain insights into their sales data, ultimately enhancing overall operational efficiency and profitability.",
    category: [
      {
        id: 1,
        name: "Employee Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 2,
        name: "Customer Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 3,
        name: "Suppliers Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 4,
        name: "Product Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 5,
        name: "Barcode Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 6,
        name: "Purchase Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 7,
        name: "Inventory Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 8,
        name: "Invoicing/Sales Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 9,
        name: "Accounts Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 10,
        name: "Repairing",
        icon: "bi bi-check-circle icon",
      },
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 23,
    icon: "bi bi-clipboard-data-fill",
    slug: "point-of-sales-software",
    logo: "/img/brands/1.png",
    tag: "Retail Market",
    social: {
      fb: "",
      twitter: "https://twitter.com/Dokanpos",
      youtube: "",
      linkedin: "https://www.linkedin.com/showcase/dokanpos-pos-software",
    },
    title: "F/E-commerce Pos",
    projectName: "Dokan Pos",
    projectUrl: "https://dokanpos.com",
    watchUrl:
      "https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FDokanpos%2Fvideos%2F1406391740297377%2F&show_text=false&width=560&t=0",
    description:
      "F/E-commerce Point of sale (POS) software is a specialized application designed to streamline and manage retail transactions. It enables businesses to efficiently process sales, track inventory, accept payments, generate receipts, and often includes reporting and analytics tools for better business management. POS software helps businesses improve customer service, reduce errors, and gain insights into their sales data, ultimately enhancing overall operational efficiency and profitability.",
    category: [
      {
        id: 1,
        name: "Employee Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 2,
        name: "Customer Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 3,
        name: "Suppliers Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 4,
        name: "Product Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 5,
        name: "Barcode Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 6,
        name: "Purchase Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 7,
        name: "Inventory Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 8,
        name: "Invoicing/Sales Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 9,
        name: "Accounts Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 10,
        name: "Repairing",
        icon: "bi bi-check-circle icon",
      },
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 24,
    icon: "bi bi-clipboard-data-fill",
    slug: "point-of-sales-software",
    logo: "/img/brands/1.png",
    tag: "Retail Market",
    social: {
      fb: "",
      twitter: "https://twitter.com/Dokanpos",
      youtube: "",
      linkedin: "https://www.linkedin.com/showcase/dokanpos-pos-software",
    },
    title: "Fashion House Pos",
    projectName: "Dokan Pos",
    projectUrl: "https://dokanpos.com",
    watchUrl:
      "https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FDokanpos%2Fvideos%2F1406391740297377%2F&show_text=false&width=560&t=0",
    description:
      "Fashion House Point of sale (POS) software is a specialized application designed to streamline and manage retail transactions. It enables businesses to efficiently process sales, track inventory, accept payments, generate receipts, and often includes reporting and analytics tools for better business management. POS software helps businesses improve customer service, reduce errors, and gain insights into their sales data, ultimately enhancing overall operational efficiency and profitability.",
    category: [
      {
        id: 1,
        name: "Employee Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 2,
        name: "Customer Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 3,
        name: "Suppliers Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 4,
        name: "Product Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 5,
        name: "Barcode Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 6,
        name: "Purchase Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 7,
        name: "Inventory Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 8,
        name: "Invoicing/Sales Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 9,
        name: "Accounts Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 10,
        name: "Repairing",
        icon: "bi bi-check-circle icon",
      },
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 25,
    icon: "bi bi-clipboard-data-fill",
    slug: "point-of-sales-software",
    logo: "/img/brands/1.png",
    tag: "Retail Market",
    social: {
      fb: "",
      twitter: "https://twitter.com/Dokanpos",
      youtube: "",
      linkedin: "https://www.linkedin.com/showcase/dokanpos-pos-software",
    },
    title: "Grocery Shop Pos",
    projectName: "Dokan Pos",
    projectUrl: "https://dokanpos.com",
    watchUrl:
      "https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FDokanpos%2Fvideos%2F1406391740297377%2F&show_text=false&width=560&t=0",
    description:
      "Grocery Shop Point of sale (POS) software is a specialized application designed to streamline and manage retail transactions. It enables businesses to efficiently process sales, track inventory, accept payments, generate receipts, and often includes reporting and analytics tools for better business management. POS software helps businesses improve customer service, reduce errors, and gain insights into their sales data, ultimately enhancing overall operational efficiency and profitability.",
    category: [
      {
        id: 1,
        name: "Employee Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 2,
        name: "Customer Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 3,
        name: "Suppliers Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 4,
        name: "Product Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 5,
        name: "Barcode Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 6,
        name: "Purchase Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 7,
        name: "Inventory Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 8,
        name: "Invoicing/Sales Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 9,
        name: "Accounts Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 10,
        name: "Repairing",
        icon: "bi bi-check-circle icon",
      },
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
  {
    id: 26,
    icon: "bi bi-clipboard-data-fill",
    slug: "point-of-sales-software",
    logo: "/img/brands/1.png",
    tag: "Retail Market",
    social: {
      fb: "",
      twitter: "https://twitter.com/Dokanpos",
      youtube: "",
      linkedin: "https://www.linkedin.com/showcase/dokanpos-pos-software",
    },
    title: "Book Shop Pos",
    projectName: "Dokan Pos",
    projectUrl: "https://dokanpos.com",
    watchUrl:
      "https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FDokanpos%2Fvideos%2F1406391740297377%2F&show_text=false&width=560&t=0",
    description:
      "Book Shop Point of sale (POS) software is a specialized application designed to streamline and manage retail transactions. It enables businesses to efficiently process sales, track inventory, accept payments, generate receipts, and often includes reporting and analytics tools for better business management. POS software helps businesses improve customer service, reduce errors, and gain insights into their sales data, ultimately enhancing overall operational efficiency and profitability.",
    category: [
      {
        id: 1,
        name: "Employee Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 2,
        name: "Customer Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 3,
        name: "Suppliers Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 4,
        name: "Product Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 5,
        name: "Barcode Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 6,
        name: "Purchase Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 7,
        name: "Inventory Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 8,
        name: "Invoicing/Sales Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 9,
        name: "Accounts Management",
        icon: "bi bi-check-circle icon",
      },
      {
        id: 10,
        name: "Repairing",
        icon: "bi bi-check-circle icon",
      },
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },

  {
    id: 27,
    icon: "bi bi-ui-checks",
    slug: "point-of-sales-software",
    logo: "/img/brands/1.png",
    tag: "Retail Market",
    title: "Restaurant Pos",
    projectName: "Dokan Pos",
    watchUrl:
      "https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FDokanpos%2Fvideos%2F1406391740297377%2F&show_text=false&width=560&t=0",
    description:
      "Restaurant Point of sale (POS) software is a specialized application designed to streamline and manage retail transactions. It enables businesses to efficiently process sales, track inventory, accept payments, generate receipts, and often includes reporting and analytics tools for better business management. POS software helps businesses improve customer service, reduce errors, and gain insights into their sales data, ultimately enhancing overall operational efficiency and profitability.",
    features: [
      "Employee Management",
      "Table Reservation",
      "Kitchen Management",
      "Order Management",
      "Inventory Management ",
      "Collection Management",
      "Customer Management",
      "Analytics and reporting",
      "Sales and menu analytics",
    ],
    images: [
      "/product/pos/1.png",
      "/product/pos/2.png",
      "/product/pos/3.png",
      "/product/pos/4.png",
      "/product/pos/5.png",
      "/product/pos/6.png",
    ],
  },
];

export default ServicesData;
